import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>DESAFIO 1 - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-gradient-to-l from-[#574AE8] to-[#3EA1DB] ">
        <div className="px-5 md:px-0 max-w-[900px] m-auto flex flex-col text-2xl text-white py-10 gap-y-16">
          <div className="flex place-content-between w-full">
            <div>Codelândia</div>
            <div>blog</div>
          </div>
          <div>
            <input
              type="text"
              placeholder="Pesquisar no Blog"
              className="appearance-none w-full bg-opacity-20 bg-white text-lg rounded-md transition placeholder:text-white leading-tight focus:outline-none focus:bg-opacity-30 focus:border-purple-500 py-5 px-4"
            ></input>
          </div>
        </div>
      </header>
      <main className="bg-[#F9F9F9] w-full">
        <div className="px-5 md:px-0 flex max-w-[900px] flex-col m-auto py-24">
          <div className="bg-white p-6">
            <p></p>
          </div>
        </div>
      </main>
    </div>
  );
}
